In [1]:
import pandas as pd
df = pd.read_csv('Loan_default.csv')

In [2]:
df.columns

Index(['LoanID', 'Age', 'Income', 'LoanAmount', 'CreditScore',
       'MonthsEmployed', 'NumCreditLines', 'InterestRate', 'LoanTerm',
       'DTIRatio', 'Education', 'EmploymentType', 'MaritalStatus',
       'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner',
       'Default'],
      dtype='str')

In [3]:
df['MaritalStatus']

0         Divorced
1          Married
2         Divorced
3          Married
4         Divorced
            ...
255342     Married
255343    Divorced
255344     Married
255345      Single
255346    Divorced
Name: MaritalStatus, Length: 255347, dtype: str

In [3]:
df.groupby(['Education','MaritalStatus']).groups

{("Bachelor's",
  'Divorced'): Index([     0,      4,      8,     18,     28,     34,     65,     69,     72,
            80,
        ...
        255221, 255225, 255240, 255252, 255273, 255274, 255293, 255308, 255330,
        255346],
       dtype='int64', length=21070),
 ("Bachelor's",
  'Married'): Index([    21,     26,     29,     44,     51,     67,     98,    100,    103,
           108,
        ...
        255194, 255256, 255266, 255268, 255270, 255295, 255298, 255312, 255331,
        255342],
       dtype='int64', length=21715),
 ("Bachelor's",
  'Single'): Index([     6,     24,     39,     53,     54,     56,     64,     95,     97,
           107,
        ...
        255209, 255219, 255245, 255263, 255264, 255272, 255276, 255288, 255299,
        255336],
       dtype='int64', length=21581),
 ('High School',
  'Divorced'): Index([    30,     42,     58,     59,     60,     73,     83,     85,     86,
            89,
        ...
        255234, 255254, 255289, 255292, 255309, 255327, 255328, 255339, 255341,
        255343],
       dtype='int64', length=21477),
 ('High School',
  'Married'): Index([     3,      9,     10,     22,     43,     46,     49,     66,     68,
            70,
        ...
        255214, 255233, 255236, 255275, 255282, 255291, 255301, 255310, 255325,
        255344],
       dtype='int64', length=21179),
 ('High School',
  'Single'): Index([     5,     13,     19,     27,     45,     57,     71,     74,     82,
            88,
        ...
        255247, 255248, 255249, 255269, 255315, 255321, 255326, 255329, 255335,
        255345],
       dtype='int64', length=21247),
 ("Master's",
  'Divorced'): Index([     2,     12,     14,     31,     37,     47,     63,     87,     91,
            92,
        ...
        255246, 255260, 255265, 255271, 255278, 255281, 255297, 255305, 255313,
        255317],
       dtype='int64', length=21131),
 ("Master's",
  'Married'): Index([     1,     15,     25,     32,     36,     61,     75,     96,    121,
           122,
        ...
        255186, 255193, 255229, 255232, 255242, 255259, 255286, 255296, 255322,
        255340],
       dtype='int64', length=21284),
 ("Master's",
  'Single'): Index([    17,     35,     40,     78,    109,    137,    142,    147,    172,
           176,
        ...
        255253, 255257, 255258, 255261, 255267, 255277, 255287, 255303, 255307,
        255316],
       dtype='int64', length=21126),
 ('PhD',
  'Divorced'): Index([    11,     20,     33,     38,     50,     84,    114,    118,    125,
           148,
        ...
        255241, 255243, 255251, 255280, 255283, 255306, 255311, 255324, 255334,
        255338],
       dtype='int64', length=21355),
 ('PhD',
  'Married'): Index([     7,     41,     52,     55,     77,     79,    104,    115,    126,
           128,
        ...
        255201, 255216, 255227, 255262, 255284, 255302, 255314, 255319, 255323,
        255333],
       dtype='int64', length=21124),
 ('PhD',
  'Single'): Index([    16,     23,     48,     62,     93,     94,    102,    119,    129,
           152,
        ...
        255279, 255285, 255290, 255294, 255300, 255304, 255318, 255320, 255332,
        255337],
       dtype='int64', length=21058)}

In [5]:
df['MaritalStatus'].nunique()

3

In [6]:
df['MaritalStatus'].unique()

<StringArray>
['Divorced', 'Married', 'Single']
Length: 3, dtype: str

In [3]:
print(df.set_index('Income'))

            LoanID  Age  LoanAmount  CreditScore  MonthsEmployed  \
Income
85994   I38PQUQS96   56       50587          520              80
50432   HPSK72WA7R   69      124440          458              15
84208   C1OZ6DPJ8Y   46      129188          451              26
31713   V2KKSFM3UN   32       44799          743               0
20437   EY08JDHTZP   60        9139          633               8
...            ...  ...         ...          ...             ...
37979   8C6S86ESGC   19      210682          541             109
51953   98R4KDHNND   32      189899          511              14
84820   XQK1UUUNGP   56      208294          597              70
85109   JAO28CPL4H   42       60575          809              40
22418   ZTH91CGL0B   62       18481          636             113

        NumCreditLines  InterestRate  LoanTerm  DTIRatio    Education  \
Income
85994                4         15.23        36      0.44   Bachelor's
50432                1          4.81        60      0.68     Master's
84208                3         21.17        24      0.31     Master's
31713                3          7.07        24      0.23  High School
20437                4          6.51        48      0.73   Bachelor's
...                ...           ...       ...       ...          ...
37979                4         14.11        12      0.85   Bachelor's
51953                2         11.55        24      0.21  High School
84820                3          5.29        60      0.50  High School
85109                1         20.90        48      0.44  High School
22418                2          6.73        12      0.48   Bachelor's

       EmploymentType MaritalStatus HasMortgage HasDependents LoanPurpose  \
Income
85994       Full-time      Divorced         Yes           Yes       Other
50432       Full-time       Married          No            No       Other
84208      Unemployed      Divorced         Yes           Yes        Auto
31713       Full-time       Married          No            No    Business
20437      Unemployed      Divorced          No           Yes        Auto
...               ...           ...         ...           ...         ...
37979       Full-time       Married          No            No       Other
51953       Part-time      Divorced          No            No        Home
84820   Self-employed       Married         Yes           Yes        Auto
85109       Part-time        Single         Yes           Yes       Other
22418      Unemployed      Divorced         Yes            No   Education

       HasCoSigner  Default
Income
85994          Yes        0
50432          Yes        0
84208           No        1
31713           No        0
20437           No        0
...            ...      ...
37979           No        0
51953           No        1
84820          Yes        0
85109           No        0
22418          Yes        0

[255347 rows x 17 columns]

In [4]:
print(df.reset_index())

         index      LoanID  Age  Income  LoanAmount  CreditScore  \
0            0  I38PQUQS96   56   85994       50587          520
1            1  HPSK72WA7R   69   50432      124440          458
2            2  C1OZ6DPJ8Y   46   84208      129188          451
3            3  V2KKSFM3UN   32   31713       44799          743
4            4  EY08JDHTZP   60   20437        9139          633
...        ...         ...  ...     ...         ...          ...
255342  255342  8C6S86ESGC   19   37979      210682          541
255343  255343  98R4KDHNND   32   51953      189899          511
255344  255344  XQK1UUUNGP   56   84820      208294          597
255345  255345  JAO28CPL4H   42   85109       60575          809
255346  255346  ZTH91CGL0B   62   22418       18481          636

        MonthsEmployed  NumCreditLines  InterestRate  LoanTerm  DTIRatio  \
0                   80               4         15.23        36      0.44
1                   15               1          4.81        60      0.68
2                   26               3         21.17        24      0.31
3                    0               3          7.07        24      0.23
4                    8               4          6.51        48      0.73
...                ...             ...           ...       ...       ...
255342             109               4         14.11        12      0.85
255343              14               2         11.55        24      0.21
255344              70               3          5.29        60      0.50
255345              40               1         20.90        48      0.44
255346             113               2          6.73        12      0.48

          Education EmploymentType MaritalStatus HasMortgage HasDependents  \
0        Bachelor's      Full-time      Divorced         Yes           Yes
1          Master's      Full-time       Married          No            No
2          Master's     Unemployed      Divorced         Yes           Yes
3       High School      Full-time       Married          No            No
4        Bachelor's     Unemployed      Divorced          No           Yes
...             ...            ...           ...         ...           ...
255342   Bachelor's      Full-time       Married          No            No
255343  High School      Part-time      Divorced          No            No
255344  High School  Self-employed       Married         Yes           Yes
255345  High School      Part-time        Single         Yes           Yes
255346   Bachelor's     Unemployed      Divorced         Yes            No

       LoanPurpose HasCoSigner  Default
0            Other         Yes        0
1            Other         Yes        0
2             Auto          No        1
3         Business          No        0
4             Auto          No        0
...            ...         ...      ...
255342       Other          No        0
255343        Home          No        1
255344        Auto         Yes        0
255345       Other          No        0
255346   Education         Yes        0

[255347 rows x 19 columns]

In [6]:
df1 = pd.DataFrame(df)
print(df1.shape)

(255347, 18)

In [7]:
df1.head(20)

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0
5,A9S62RQ7US,25,90298,90448,720,18,2,22.72,24,0.10,High School,Unemployed,Single,Yes,No,Business,Yes,1
6,H8GXPAOS71,38,111188,177025,429,80,1,19.11,12,0.16,Bachelor's,Unemployed,Single,Yes,No,Home,Yes,0
7,0HGZQKJ36W,56,126802,155511,531,67,4,8.15,60,0.43,PhD,Full-time,Married,No,No,Home,Yes,0
8,1R0N3LGNRJ,36,42053,92357,827,83,1,23.94,48,0.20,Bachelor's,Self-employed,Divorced,Yes,No,Education,No,1
9,CM9L1GTT2P,40,132784,228510,480,114,4,9.09,48,0.33,High School,Self-employed,Married,Yes,No,Other,Yes,0
10,IA35XVH6ZO,28,140466,163781,652,94,2,9.08,48,0.23,High School,Unemployed,Married,No,No,Education,No,0
11,Y8UETC3LSG,28,149227,139759,375,56,3,5.84,36,0.80,PhD,Full-time,Divorced,No,No,Education,Yes,1
12,RM6QSRHIYP,41,23265,63527,829,87,4,9.73,60,0.45,Master's,Full-time,Divorced,Yes,No,Auto,Yes,0
13,GX5YQOGROM,53,117550,95744,395,112,4,3.58,24,0.73,High School,Unemployed,Single,No,No,Auto,Yes,0
14,X0BVPZLDC0,57,139699,88143,635,112,4,5.63,48,0.20,Master's,Part-time,Divorced,No,No,Home,No,0
15,O5DM5MPPNA,41,74064,230883,432,31,2,5.00,60,0.89,Master's,Unemployed,Married,Yes,No,Auto,No,0
16,ZDDRGVTEXS,20,119704,25697,313,49,1,9.63,24,0.28,PhD,Unemployed,Single,Yes,No,Home,No,0
17,9V0FJW7QPB,39,33015,10889,811,106,2,13.56,60,0.66,Master's,Self-employed,Single,Yes,No,Other,No,0
18,O1IKKLC69B,19,40718,78515,319,119,2,14.00,24,0.17,Bachelor's,Self-employed,Divorced,Yes,No,Education,No,1
19,F7487UU2BF,41,123419,161146,376,65,4,16.96,60,0.39,High School,Self-employed,Single,Yes,No,Other,Yes,0

In [8]:
df1.tail(20)

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
255327,BLRBOJV956,53,72119,157179,459,56,4,4.99,36,0.46,High School,Full-time,Divorced,No,Yes,Home,No,0
255328,P3UCIPJVTB,50,21890,226684,839,62,1,5.80,48,0.65,High School,Self-employed,Divorced,Yes,No,Home,No,0
255329,QXBHNXNA9X,34,53658,187245,847,35,3,3.08,48,0.85,High School,Unemployed,Single,Yes,Yes,Auto,Yes,0
255330,QU29Z1EVQI,59,104108,13015,761,61,2,15.75,36,0.72,Bachelor's,Part-time,Divorced,Yes,No,Education,No,0
255331,FV922AXELU,48,144907,190265,683,92,2,11.12,48,0.41,Bachelor's,Self-employed,Married,Yes,No,Other,Yes,0
255332,XMA3UCYP0L,67,76558,122456,734,90,2,14.30,60,0.53,PhD,Part-time,Single,No,No,Other,Yes,0
255333,BM4B25R7EI,22,45575,43355,545,99,1,21.86,12,0.52,PhD,Unemployed,Married,Yes,Yes,Education,No,1
255334,Y5HYHQWBVP,69,34859,105905,715,25,2,20.28,48,0.35,PhD,Self-employed,Divorced,No,Yes,Business,No,0
255335,OQ99DN6JL4,41,124446,249800,650,60,4,3.32,24,0.21,High School,Unemployed,Single,Yes,No,Other,No,0
255336,NUUI6CJDZ9,60,20868,81574,584,8,2,5.21,60,0.77,Bachelor's,Part-time,Single,No,No,Business,No,0
255337,DSL4O0KAWD,64,73743,140354,300,0,2,4.12,12,0.24,PhD,Self-employed,Single,Yes,No,Education,Yes,0
255338,6V8S5IUS63,68,21711,168231,352,78,2,9.71,60,0.36,PhD,Full-time,Divorced,Yes,Yes,Home,No,0
255339,O6SWO6CBGB,51,69492,122962,348,66,2,10.83,48,0.27,High School,Part-time,Divorced,No,No,Home,No,0
255340,48LOOK4VR1,41,61809,119238,444,34,2,19.99,36,0.31,Master's,Part-time,Married,Yes,Yes,Auto,Yes,0
255341,AKXAXQN7PG,40,129890,116119,701,38,3,9.91,24,0.23,High School,Part-time,Divorced,Yes,No,Home,Yes,1
255342,8C6S86ESGC,19,37979,210682,541,109,4,14.11,12,0.85,Bachelor's,Full-time,Married,No,No,Other,No,0
255343,98R4KDHNND,32,51953,189899,511,14,2,11.55,24,0.21,High School,Part-time,Divorced,No,No,Home,No,1
255344,XQK1UUUNGP,56,84820,208294,597,70,3,5.29,60,0.50,High School,Self-employed,Married,Yes,Yes,Auto,Yes,0
255345,JAO28CPL4H,42,85109,60575,809,40,1,20.90,48,0.44,High School,Part-time,Single,Yes,Yes,Other,No,0
255346,ZTH91CGL0B,62,22418,18481,636,113,2,6.73,12,0.48,Bachelor's,Unemployed,Divorced,Yes,No,Education,Yes,0

In [9]:
df1.size

4596246

In [10]:
df1.ndim

2

In [10]:
df1.columns

Index(['LoanID', 'Age', 'Income', 'LoanAmount', 'CreditScore',
       'MonthsEmployed', 'NumCreditLines', 'InterestRate', 'LoanTerm',
       'DTIRatio', 'Education', 'EmploymentType', 'MaritalStatus',
       'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner',
       'Default'],
      dtype='str')

In [11]:
df1.index

RangeIndex(start=0, stop=255347, step=1)

In [12]:
df.dtypes

LoanID                str
Age                 int64
Income              int64
LoanAmount          int64
CreditScore         int64
MonthsEmployed      int64
NumCreditLines      int64
InterestRate      float64
LoanTerm            int64
DTIRatio          float64
Education             str
EmploymentType        str
MaritalStatus         str
HasMortgage           str
HasDependents         str
LoanPurpose           str
HasCoSigner           str
Default             int64
dtype: object

In [13]:
df1.values

array([['I38PQUQS96', 56, 85994, ..., 'Other', 'Yes', 0],
       ['HPSK72WA7R', 69, 50432, ..., 'Other', 'Yes', 0],
       ['C1OZ6DPJ8Y', 46, 84208, ..., 'Auto', 'No', 1],
       ...,
       ['XQK1UUUNGP', 56, 84820, ..., 'Auto', 'Yes', 0],
       ['JAO28CPL4H', 42, 85109, ..., 'Other', 'No', 0],
       ['ZTH91CGL0B', 62, 22418, ..., 'Education', 'Yes', 0]],
      shape=(255347, 18), dtype=object)

In [14]:
df1.empty

False

In [15]:
df1.T

,0,1,2,3,4,5,6,7,8,9,...,255337,255338,255339,255340,255341,255342,255343,255344,255345,255346
LoanID,I38PQUQS96,HPSK72WA7R,C1OZ6DPJ8Y,V2KKSFM3UN,EY08JDHTZP,A9S62RQ7US,H8GXPAOS71,0HGZQKJ36W,1R0N3LGNRJ,CM9L1GTT2P,...,DSL4O0KAWD,6V8S5IUS63,O6SWO6CBGB,48LOOK4VR1,AKXAXQN7PG,8C6S86ESGC,98R4KDHNND,XQK1UUUNGP,JAO28CPL4H,ZTH91CGL0B
Age,56,69,46,32,60,25,38,56,36,40,...,64,68,51,41,40,19,32,56,42,62
Income,85994,50432,84208,31713,20437,90298,111188,126802,42053,132784,...,73743,21711,69492,61809,129890,37979,51953,84820,85109,22418
LoanAmount,50587,124440,129188,44799,9139,90448,177025,155511,92357,228510,...,140354,168231,122962,119238,116119,210682,189899,208294,60575,18481
CreditScore,520,458,451,743,633,720,429,531,827,480,...,300,352,348,444,701,541,511,597,809,636
MonthsEmployed,80,15,26,0,8,18,80,67,83,114,...,0,78,66,34,38,109,14,70,40,113
NumCreditLines,4,1,3,3,4,2,1,4,1,4,...,2,2,2,2,3,4,2,3,1,2
InterestRate,15.23,4.81,21.17,7.07,6.51,22.72,19.11,8.15,23.94,9.09,...,4.12,9.71,10.83,19.99,9.91,14.11,11.55,5.29,20.9,6.73
LoanTerm,36,60,24,24,48,24,12,60,48,48,...,12,60,48,36,24,12,24,60,48,12
DTIRatio,0.44,0.68,0.31,0.23,0.73,0.1,0.16,0.43,0.2,0.33,...,0.24,0.36,0.27,0.31,0.23,0.85,0.21,0.5,0.44,0.48
Education,Bachelor's,Master's,Master's,High School,Bachelor's,High School,Bachelor's,PhD,Bachelor's,High School,...,PhD,PhD,High School,Master's,High School,Bachelor's,High School,High School,High School,Bachelor's
EmploymentType,Full-time,Full-time,Unemployed,Full-time,Unemployed,Unemployed,Unemployed,Full-time,Self-employed,Self-employed,...,Self-employed,Full-time,Part-time,Part-time,Part-time,Full-time,Part-time,Self-employed,Part-time,Unemployed
MaritalStatus,Divorced,Married,Divorced,Married,Divorced,Single,Single,Married,Divorced,Married,...,Single,Divorced,Divorced,Married,Divorced,Married,Divorced,Married,Single,Divorced
HasMortgage,Yes,No,Yes,No,No,Yes,Yes,No,Yes,Yes,...,Yes,Yes,No,Yes,Yes,No,No,Yes,Yes,Yes
HasDependents,Yes,No,Yes,No,Yes,No,No,No,No,No,...,No,Yes,No,Yes,No,No,No,Yes,Yes,No
LoanPurpose,Other,Other,Auto,Business,Auto,Business,Home,Home,Education,Other,...,Education,Home,Home,Auto,Home,Other,Home,Auto,Other,Education
HasCoSigner,Yes,Yes,No,No,No,Yes,Yes,Yes,No,Yes,...,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes
Default,0,0,1,0,0,1,0,0,1,0,...,0,0,0,0,1,0,1,0,0,0

In [17]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 18 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   LoanID          255347 non-null  str
 1   Age             255347 non-null  int64
 2   Income          255347 non-null  int64
 3   LoanAmount      255347 non-null  int64
 4   CreditScore     255347 non-null  int64
 5   MonthsEmployed  255347 non-null  int64
 6   NumCreditLines  255347 non-null  int64
 7   InterestRate    255347 non-null  float64
 8   LoanTerm        255347 non-null  int64
 9   DTIRatio        255347 non-null  float64
 10  Education       255347 non-null  str
 11  EmploymentType  255347 non-null  str
 12  MaritalStatus   255347 non-null  str
 13  HasMortgage     255347 non-null  str
 14  HasDependents   255347 non-null  str
 15  LoanPurpose     255347 non-null  str
 16  HasCoSigner     255347 non-null  str
 17  Default         255347 non-null  int64
dtypes: float64(2), int64(8), str(8)
memory usage: 35.1 MB

In [20]:
df1.describe()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Default
count,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000
mean,43.498306,82499.304597,127578.865512,574.264346,59.541976,2.501036,13.492773,36.025894,0.500212,0.116128
std,14.990258,38963.013729,70840.706142,158.903867,34.643376,1.117018,6.636443,16.969330,0.230917,0.320379
min,18.000000,15000.000000,5000.000000,300.000000,0.000000,1.000000,2.000000,12.000000,0.100000,0.000000
25%,31.000000,48825.500000,66156.000000,437.000000,30.000000,2.000000,7.770000,24.000000,0.300000,0.000000
50%,43.000000,82466.000000,127556.000000,574.000000,60.000000,2.000000,13.460000,36.000000,0.500000,0.000000
75%,56.000000,116219.000000,188985.000000,712.000000,90.000000,3.000000,19.250000,48.000000,0.700000,0.000000
max,69.000000,149999.000000,249999.000000,849.000000,119.000000,4.000000,25.000000,60.000000,0.900000,1.000000

In [22]:
### Given A Random rows
df1.sample()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
103371,X7B46LHNJH,67,100568,76433,749,20,1,19.41,24,0.59,Bachelor's,Self-employed,Single,Yes,No,Education,Yes,0

In [23]:
df1.count()

LoanID            255347
Age               255347
Income            255347
LoanAmount        255347
CreditScore       255347
MonthsEmployed    255347
NumCreditLines    255347
InterestRate      255347
LoanTerm          255347
DTIRatio          255347
Education         255347
EmploymentType    255347
MaritalStatus     255347
HasMortgage       255347
HasDependents     255347
LoanPurpose       255347
HasCoSigner       255347
Default           255347
dtype: int64

In [24]:
df1.isnull()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255342,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
255343,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
255344,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
255345,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
255346,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [25]:
df1.notnull()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255342,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
255343,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
255344,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
255345,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
255346,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

In [31]:
df.shape[0]

255347

In [32]:
df.shape[1]

18